version: '3.9'

services:
   db:
    image: postgres:latest
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234567890
    volumes:
      - .db:/var/lib/postgresql/data
    ports:
      - 5432:5432

   api:
    container_name: backend
    build: ./readcode-backend/
    restart: always
    #volumes:
      # ./backend/: veut dire qu'on mount directory ./backend/ au WORKDIR de l'image /usr/src/app 
    #  - "./backend/:/usr/src/app"
    #  - /usr/src/app/node_modules/

    #volumes:
    #  - ./readcode-backend/:/usr/src/app
    #  - /usr/src/app/node_modules
    ports:
      - 8080:8080
    # variables d'environnement
    environment:
      - NODE_ENV=PROD
    depends_on:
      - db
   # Front-end React
   frontend:
    container_name: frontend
    build: ./readcode-frontend/
    # Tentative d'implementer le livereload
    #stdin_open: true
    #volumes:
    #  - ./readcode-frontend/:/usr/src/app:delegated
    #  - /usr/src/app/node_modules
    #environment:
    #  - CHOKIDAR_USEPOLLING=true
    ports: 
      - 3000:3000
    depends_on:
      - api

volumes:
  dbdata6: {}
